version: '3'
services:
  mysql:
    image: 'mysql:8.0.35'
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=campus
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword
    volumes:
      - ./.data/mysql:/var/lib/mysql
