package com.ehyundai.app.adapter.inspectedpost;

import com.ehyundai.app.adapter.common.OperationType;
import com.ehyundai.app.inspectedpost.model.InspectedPost;
import com.ehyundai.app.post.model.Post;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;
import java.util.List;

@AllArgsConstructor
@NoArgsConstructor
@Data
public class InspectedPostMessage {
    private Long id;
    private Payload payload;
    private OperationType operationType;

    @AllArgsConstructor
    @NoArgsConstructor
    @Data
    public static class Payload {
        private Post post;
        private String categoryName;
        private List<String> autoGeneratedTags;
        private LocalDateTime inspectedAt;
    }

    public InspectedPost toModel() {
        return new InspectedPost(
            this.payload.getPost(),
            this.payload.getCategoryName(),
            this.payload.getAutoGeneratedTags(),
            this.payload.getInspectedAt()
        );
    }
}
